import { type ReactNode } from "react";
import { Printer, ArrowLeft } from "lucide-react";
import { Link } from "@tanstack/react-router";

export function PrintLayout({
  title,
  subtitle,
  org,
  backTo = "/report/exports",
  children,
}: {
  title: string;
  subtitle?: string;
  org: string;
  backTo?: string;
  children: ReactNode;
}) {
  const today = new Date().toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric",
  });

  return (
    <div className="min-h-screen bg-slate-100 print-page">
      {/* Floating action bar — hidden when printing */}
      <div className="no-print sticky top-0 z-20 bg-white border-b border-slate-200 px-6 py-3 flex items-center justify-between">
        <Link
          to={backTo}
          className="flex items-center gap-2 text-sm text-slate-600 hover:text-slate-900"
        >
          <ArrowLeft className="size-4" /> Back to Exports
        </Link>
        <button
          onClick={() => window.print()}
          className="flex items-center gap-2 px-4 py-2 bg-brand-deep text-white rounded-lg text-sm font-medium hover:bg-brand-deep/90"
        >
          <Printer className="size-4" /> Print / Save as PDF
        </button>
      </div>

      {/* Document */}
      <div className="max-w-[8.5in] mx-auto bg-white shadow-sm print:shadow-none my-6 print:my-0 px-10 py-12 print:p-0 text-slate-900">
        {/* Cover header */}
        <header className="text-center pb-8 mb-8 border-b border-slate-200">
          <p className="text-[10px] uppercase tracking-[0.3em] text-slate-500 font-bold">
            {title}
          </p>
          <h1 className="font-serif italic text-5xl text-brand-deep mt-2">{org}</h1>
          {subtitle && <p className="text-sm text-slate-600 mt-3">{subtitle}</p>}
          <p className="text-xs text-slate-500 mt-3">{today}</p>
        </header>

        {children}

        <footer className="mt-12 pt-6 border-t border-slate-200 text-[10px] text-slate-500 text-center">
          Generated by NMM Navigator · {today}
        </footer>
      </div>
    </div>
  );
}

export function PrintSection({
  title,
  children,
}: {
  title: string;
  children: ReactNode;
}) {
  return (
    <section className="mb-8 avoid-break">
      <h2 className="font-serif italic text-2xl text-brand-deep border-b border-slate-200 pb-2 mb-4">
        {title}
      </h2>
      {children}
    </section>
  );
}

export function PrintKV({
  label,
  value,
}: {
  label: string;
  value: ReactNode;
}) {
  return (
    <div className="grid grid-cols-[180px_1fr] gap-4 py-2 border-b border-slate-100">
      <dt className="text-xs uppercase tracking-wider text-slate-500 font-semibold">
        {label}
      </dt>
      <dd className="text-sm text-slate-800">{value || <span className="text-slate-300">—</span>}</dd>
    </div>
  );
}
