/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedValuesRouteImport } from './routes/_authenticated/values'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedReportStoriesRouteImport } from './routes/_authenticated/report.stories'
import { Route as AuthenticatedReportMonthlyReviewRouteImport } from './routes/_authenticated/report.monthly-review'
import { Route as AuthenticatedReportInsightsRouteImport } from './routes/_authenticated/report.insights'
import { Route as AuthenticatedReportExportsRouteImport } from './routes/_authenticated/report.exports'
import { Route as AuthenticatedReportBenchmarksRouteImport } from './routes/_authenticated/report.benchmarks'
import { Route as AuthenticatedPlanTheoryOfChangeRouteImport } from './routes/_authenticated/plan.theory-of-change'
import { Route as AuthenticatedPlanSwotRouteImport } from './routes/_authenticated/plan.swot'
import { Route as AuthenticatedPlanStakeholdersRouteImport } from './routes/_authenticated/plan.stakeholders'
import { Route as AuthenticatedPlanRisksRouteImport } from './routes/_authenticated/plan.risks'
import { Route as AuthenticatedPlanPrioritiesRouteImport } from './routes/_authenticated/plan.priorities'
import { Route as AuthenticatedPlanNarrativeRouteImport } from './routes/_authenticated/plan.narrative'
import { Route as AuthenticatedPlanKpisRouteImport } from './routes/_authenticated/plan.kpis'
import { Route as AuthenticatedPlanBuilderRouteImport } from './routes/_authenticated/plan.builder'
import { Route as AuthenticatedInviteTokenRouteImport } from './routes/_authenticated/invite.$token'
import { Route as AuthenticatedGovernanceStaffSuccessionRouteImport } from './routes/_authenticated/governance.staff-succession'
import { Route as AuthenticatedGovernancePoliciesRouteImport } from './routes/_authenticated/governance.policies'
import { Route as AuthenticatedGovernanceMeetingsRouteImport } from './routes/_authenticated/governance.meetings'
import { Route as AuthenticatedGovernanceDecisionsRouteImport } from './routes/_authenticated/governance.decisions'
import { Route as AuthenticatedGovernanceBoardMatrixRouteImport } from './routes/_authenticated/governance.board-matrix'
import { Route as AuthenticatedFundScenariosRouteImport } from './routes/_authenticated/fund.scenarios'
import { Route as AuthenticatedFundReservesRouteImport } from './routes/_authenticated/fund.reserves'
import { Route as AuthenticatedFundProgramCostsRouteImport } from './routes/_authenticated/fund.program-costs'
import { Route as AuthenticatedFundProformaRouteImport } from './routes/_authenticated/fund.proforma'
import { Route as AuthenticatedFundPipelineRouteImport } from './routes/_authenticated/fund.pipeline'
import { Route as AuthenticatedFundGrantsRouteImport } from './routes/_authenticated/fund.grants'
import { Route as AuthenticatedFundGrantBankRouteImport } from './routes/_authenticated/fund.grant-bank'
import { Route as AuthenticatedFundGapRouteImport } from './routes/_authenticated/fund.gap'
import { Route as AuthenticatedFundDonorSegmentsRouteImport } from './routes/_authenticated/fund.donor-segments'
import { Route as AuthenticatedFundBudgetRouteImport } from './routes/_authenticated/fund.budget'
import { Route as AuthenticatedFundAsksBankRouteImport } from './routes/_authenticated/fund.asks-bank'
import { Route as AuthenticatedExecuteTouchpointsRouteImport } from './routes/_authenticated/execute.touchpoints'
import { Route as AuthenticatedExecuteTasksRouteImport } from './routes/_authenticated/execute.tasks'
import { Route as AuthenticatedExecuteProgramsRouteImport } from './routes/_authenticated/execute.programs'
import { Route as AuthenticatedExecuteOkrsRouteImport } from './routes/_authenticated/execute.okrs'
import { Route as AuthenticatedExecuteGanttRouteImport } from './routes/_authenticated/execute.gantt'
import { Route as AuthenticatedExecuteComplianceRouteImport } from './routes/_authenticated/execute.compliance'
import { Route as AuthenticatedExecuteCoffeeChatsRouteImport } from './routes/_authenticated/execute.coffee-chats'
import { Route as AuthenticatedExecuteCalendarRouteImport } from './routes/_authenticated/execute.calendar'
import { Route as AuthenticatedAssessRevenueHhiRouteImport } from './routes/_authenticated/assess.revenue-hhi'
import { Route as AuthenticatedAssessProgramImpactRouteImport } from './routes/_authenticated/assess.program-impact'
import { Route as AuthenticatedAssessImpactRouteImport } from './routes/_authenticated/assess.impact'
import { Route as AuthenticatedAssessHealthRouteImport } from './routes/_authenticated/assess.health'
import { Route as AuthenticatedAssessGovernanceRouteImport } from './routes/_authenticated/assess.governance'
import { Route as AuthenticatedAssessFundraisingRouteImport } from './routes/_authenticated/assess.fundraising'
import { Route as AuthenticatedAssessFinancialRouteImport } from './routes/_authenticated/assess.financial'
import { Route as AuthenticatedAssessDigitalRouteImport } from './routes/_authenticated/assess.digital'
import { Route as AuthenticatedAssessDeiRouteImport } from './routes/_authenticated/assess.dei'
import { Route as AuthenticatedAssessCommunityRouteImport } from './routes/_authenticated/assess.community'
import { Route as AuthenticatedAssessCapacityRouteImport } from './routes/_authenticated/assess.capacity'
import { Route as AuthenticatedAssess4rsRouteImport } from './routes/_authenticated/assess.4rs'
import { Route as AuthenticatedReportPrintStrategicPlanRouteImport } from './routes/_authenticated/report.print.strategic-plan'
import { Route as AuthenticatedReportPrintRevenueDiversificationRouteImport } from './routes/_authenticated/report.print.revenue-diversification'
import { Route as AuthenticatedReportPrintProgramImpactRouteImport } from './routes/_authenticated/report.print.program-impact'
import { Route as AuthenticatedReportPrintLogicModelRouteImport } from './routes/_authenticated/report.print.logic-model'
import { Route as AuthenticatedReportPrintImpactReportRouteImport } from './routes/_authenticated/report.print.impact-report'
import { Route as AuthenticatedReportPrintGrantReadinessRouteImport } from './routes/_authenticated/report.print.grant-readiness'
import { Route as AuthenticatedReportPrintFundingGapRouteImport } from './routes/_authenticated/report.print.funding-gap'
import { Route as AuthenticatedReportPrintFunderReportRouteImport } from './routes/_authenticated/report.print.funder-report'
import { Route as AuthenticatedReportPrintFourrsReportRouteImport } from './routes/_authenticated/report.print.fourrs-report'
import { Route as AuthenticatedReportPrintFinancialSustainabilityRouteImport } from './routes/_authenticated/report.print.financial-sustainability'
import { Route as AuthenticatedReportPrintBoardPacketRouteImport } from './routes/_authenticated/report.print.board-packet'
import { Route as AuthenticatedReportPrintAnnualOperatingPlanRouteImport } from './routes/_authenticated/report.print.annual-operating-plan'
import { Route as AuthenticatedReportPrintActionPlan306090RouteImport } from './routes/_authenticated/report.print.action-plan-306090'
import { Route as AuthenticatedGovernanceMeetingsMeetingIdRouteImport } from './routes/_authenticated/governance.meetings.$meetingId'
import { Route as AuthenticatedAdminOrgsOrgIdRouteImport } from './routes/_authenticated/admin.orgs.$orgId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedValuesRoute = AuthenticatedValuesRouteImport.update({
  id: '/values',
  path: '/values',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedReportStoriesRoute =
  AuthenticatedReportStoriesRouteImport.update({
    id: '/report/stories',
    path: '/report/stories',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportMonthlyReviewRoute =
  AuthenticatedReportMonthlyReviewRouteImport.update({
    id: '/report/monthly-review',
    path: '/report/monthly-review',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportInsightsRoute =
  AuthenticatedReportInsightsRouteImport.update({
    id: '/report/insights',
    path: '/report/insights',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportExportsRoute =
  AuthenticatedReportExportsRouteImport.update({
    id: '/report/exports',
    path: '/report/exports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportBenchmarksRoute =
  AuthenticatedReportBenchmarksRouteImport.update({
    id: '/report/benchmarks',
    path: '/report/benchmarks',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlanTheoryOfChangeRoute =
  AuthenticatedPlanTheoryOfChangeRouteImport.update({
    id: '/plan/theory-of-change',
    path: '/plan/theory-of-change',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlanSwotRoute = AuthenticatedPlanSwotRouteImport.update({
  id: '/plan/swot',
  path: '/plan/swot',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanStakeholdersRoute =
  AuthenticatedPlanStakeholdersRouteImport.update({
    id: '/plan/stakeholders',
    path: '/plan/stakeholders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlanRisksRoute = AuthenticatedPlanRisksRouteImport.update({
  id: '/plan/risks',
  path: '/plan/risks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanPrioritiesRoute =
  AuthenticatedPlanPrioritiesRouteImport.update({
    id: '/plan/priorities',
    path: '/plan/priorities',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlanNarrativeRoute =
  AuthenticatedPlanNarrativeRouteImport.update({
    id: '/plan/narrative',
    path: '/plan/narrative',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlanKpisRoute = AuthenticatedPlanKpisRouteImport.update({
  id: '/plan/kpis',
  path: '/plan/kpis',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanBuilderRoute =
  AuthenticatedPlanBuilderRouteImport.update({
    id: '/plan/builder',
    path: '/plan/builder',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInviteTokenRoute =
  AuthenticatedInviteTokenRouteImport.update({
    id: '/invite/$token',
    path: '/invite/$token',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGovernanceStaffSuccessionRoute =
  AuthenticatedGovernanceStaffSuccessionRouteImport.update({
    id: '/governance/staff-succession',
    path: '/governance/staff-succession',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGovernancePoliciesRoute =
  AuthenticatedGovernancePoliciesRouteImport.update({
    id: '/governance/policies',
    path: '/governance/policies',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGovernanceMeetingsRoute =
  AuthenticatedGovernanceMeetingsRouteImport.update({
    id: '/governance/meetings',
    path: '/governance/meetings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGovernanceDecisionsRoute =
  AuthenticatedGovernanceDecisionsRouteImport.update({
    id: '/governance/decisions',
    path: '/governance/decisions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGovernanceBoardMatrixRoute =
  AuthenticatedGovernanceBoardMatrixRouteImport.update({
    id: '/governance/board-matrix',
    path: '/governance/board-matrix',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFundScenariosRoute =
  AuthenticatedFundScenariosRouteImport.update({
    id: '/fund/scenarios',
    path: '/fund/scenarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFundReservesRoute =
  AuthenticatedFundReservesRouteImport.update({
    id: '/fund/reserves',
    path: '/fund/reserves',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFundProgramCostsRoute =
  AuthenticatedFundProgramCostsRouteImport.update({
    id: '/fund/program-costs',
    path: '/fund/program-costs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFundProformaRoute =
  AuthenticatedFundProformaRouteImport.update({
    id: '/fund/proforma',
    path: '/fund/proforma',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFundPipelineRoute =
  AuthenticatedFundPipelineRouteImport.update({
    id: '/fund/pipeline',
    path: '/fund/pipeline',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFundGrantsRoute = AuthenticatedFundGrantsRouteImport.update({
  id: '/fund/grants',
  path: '/fund/grants',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFundGrantBankRoute =
  AuthenticatedFundGrantBankRouteImport.update({
    id: '/fund/grant-bank',
    path: '/fund/grant-bank',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFundGapRoute = AuthenticatedFundGapRouteImport.update({
  id: '/fund/gap',
  path: '/fund/gap',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFundDonorSegmentsRoute =
  AuthenticatedFundDonorSegmentsRouteImport.update({
    id: '/fund/donor-segments',
    path: '/fund/donor-segments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFundBudgetRoute = AuthenticatedFundBudgetRouteImport.update({
  id: '/fund/budget',
  path: '/fund/budget',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFundAsksBankRoute =
  AuthenticatedFundAsksBankRouteImport.update({
    id: '/fund/asks-bank',
    path: '/fund/asks-bank',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExecuteTouchpointsRoute =
  AuthenticatedExecuteTouchpointsRouteImport.update({
    id: '/execute/touchpoints',
    path: '/execute/touchpoints',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExecuteTasksRoute =
  AuthenticatedExecuteTasksRouteImport.update({
    id: '/execute/tasks',
    path: '/execute/tasks',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExecuteProgramsRoute =
  AuthenticatedExecuteProgramsRouteImport.update({
    id: '/execute/programs',
    path: '/execute/programs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExecuteOkrsRoute =
  AuthenticatedExecuteOkrsRouteImport.update({
    id: '/execute/okrs',
    path: '/execute/okrs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExecuteGanttRoute =
  AuthenticatedExecuteGanttRouteImport.update({
    id: '/execute/gantt',
    path: '/execute/gantt',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExecuteComplianceRoute =
  AuthenticatedExecuteComplianceRouteImport.update({
    id: '/execute/compliance',
    path: '/execute/compliance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExecuteCoffeeChatsRoute =
  AuthenticatedExecuteCoffeeChatsRouteImport.update({
    id: '/execute/coffee-chats',
    path: '/execute/coffee-chats',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExecuteCalendarRoute =
  AuthenticatedExecuteCalendarRouteImport.update({
    id: '/execute/calendar',
    path: '/execute/calendar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssessRevenueHhiRoute =
  AuthenticatedAssessRevenueHhiRouteImport.update({
    id: '/assess/revenue-hhi',
    path: '/assess/revenue-hhi',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssessProgramImpactRoute =
  AuthenticatedAssessProgramImpactRouteImport.update({
    id: '/assess/program-impact',
    path: '/assess/program-impact',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssessImpactRoute =
  AuthenticatedAssessImpactRouteImport.update({
    id: '/assess/impact',
    path: '/assess/impact',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssessHealthRoute =
  AuthenticatedAssessHealthRouteImport.update({
    id: '/assess/health',
    path: '/assess/health',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssessGovernanceRoute =
  AuthenticatedAssessGovernanceRouteImport.update({
    id: '/assess/governance',
    path: '/assess/governance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssessFundraisingRoute =
  AuthenticatedAssessFundraisingRouteImport.update({
    id: '/assess/fundraising',
    path: '/assess/fundraising',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssessFinancialRoute =
  AuthenticatedAssessFinancialRouteImport.update({
    id: '/assess/financial',
    path: '/assess/financial',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssessDigitalRoute =
  AuthenticatedAssessDigitalRouteImport.update({
    id: '/assess/digital',
    path: '/assess/digital',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssessDeiRoute = AuthenticatedAssessDeiRouteImport.update({
  id: '/assess/dei',
  path: '/assess/dei',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssessCommunityRoute =
  AuthenticatedAssessCommunityRouteImport.update({
    id: '/assess/community',
    path: '/assess/community',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssessCapacityRoute =
  AuthenticatedAssessCapacityRouteImport.update({
    id: '/assess/capacity',
    path: '/assess/capacity',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssess4rsRoute = AuthenticatedAssess4rsRouteImport.update({
  id: '/assess/4rs',
  path: '/assess/4rs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportPrintStrategicPlanRoute =
  AuthenticatedReportPrintStrategicPlanRouteImport.update({
    id: '/report/print/strategic-plan',
    path: '/report/print/strategic-plan',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportPrintRevenueDiversificationRoute =
  AuthenticatedReportPrintRevenueDiversificationRouteImport.update({
    id: '/report/print/revenue-diversification',
    path: '/report/print/revenue-diversification',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportPrintProgramImpactRoute =
  AuthenticatedReportPrintProgramImpactRouteImport.update({
    id: '/report/print/program-impact',
    path: '/report/print/program-impact',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportPrintLogicModelRoute =
  AuthenticatedReportPrintLogicModelRouteImport.update({
    id: '/report/print/logic-model',
    path: '/report/print/logic-model',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportPrintImpactReportRoute =
  AuthenticatedReportPrintImpactReportRouteImport.update({
    id: '/report/print/impact-report',
    path: '/report/print/impact-report',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportPrintGrantReadinessRoute =
  AuthenticatedReportPrintGrantReadinessRouteImport.update({
    id: '/report/print/grant-readiness',
    path: '/report/print/grant-readiness',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportPrintFundingGapRoute =
  AuthenticatedReportPrintFundingGapRouteImport.update({
    id: '/report/print/funding-gap',
    path: '/report/print/funding-gap',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportPrintFunderReportRoute =
  AuthenticatedReportPrintFunderReportRouteImport.update({
    id: '/report/print/funder-report',
    path: '/report/print/funder-report',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportPrintFourrsReportRoute =
  AuthenticatedReportPrintFourrsReportRouteImport.update({
    id: '/report/print/fourrs-report',
    path: '/report/print/fourrs-report',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportPrintFinancialSustainabilityRoute =
  AuthenticatedReportPrintFinancialSustainabilityRouteImport.update({
    id: '/report/print/financial-sustainability',
    path: '/report/print/financial-sustainability',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportPrintBoardPacketRoute =
  AuthenticatedReportPrintBoardPacketRouteImport.update({
    id: '/report/print/board-packet',
    path: '/report/print/board-packet',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportPrintAnnualOperatingPlanRoute =
  AuthenticatedReportPrintAnnualOperatingPlanRouteImport.update({
    id: '/report/print/annual-operating-plan',
    path: '/report/print/annual-operating-plan',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportPrintActionPlan306090Route =
  AuthenticatedReportPrintActionPlan306090RouteImport.update({
    id: '/report/print/action-plan-306090',
    path: '/report/print/action-plan-306090',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGovernanceMeetingsMeetingIdRoute =
  AuthenticatedGovernanceMeetingsMeetingIdRouteImport.update({
    id: '/$meetingId',
    path: '/$meetingId',
    getParentRoute: () => AuthenticatedGovernanceMeetingsRoute,
  } as any)
const AuthenticatedAdminOrgsOrgIdRoute =
  AuthenticatedAdminOrgsOrgIdRouteImport.update({
    id: '/orgs/$orgId',
    path: '/orgs/$orgId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/team': typeof AuthenticatedTeamRoute
  '/values': typeof AuthenticatedValuesRoute
  '/assess/4rs': typeof AuthenticatedAssess4rsRoute
  '/assess/capacity': typeof AuthenticatedAssessCapacityRoute
  '/assess/community': typeof AuthenticatedAssessCommunityRoute
  '/assess/dei': typeof AuthenticatedAssessDeiRoute
  '/assess/digital': typeof AuthenticatedAssessDigitalRoute
  '/assess/financial': typeof AuthenticatedAssessFinancialRoute
  '/assess/fundraising': typeof AuthenticatedAssessFundraisingRoute
  '/assess/governance': typeof AuthenticatedAssessGovernanceRoute
  '/assess/health': typeof AuthenticatedAssessHealthRoute
  '/assess/impact': typeof AuthenticatedAssessImpactRoute
  '/assess/program-impact': typeof AuthenticatedAssessProgramImpactRoute
  '/assess/revenue-hhi': typeof AuthenticatedAssessRevenueHhiRoute
  '/execute/calendar': typeof AuthenticatedExecuteCalendarRoute
  '/execute/coffee-chats': typeof AuthenticatedExecuteCoffeeChatsRoute
  '/execute/compliance': typeof AuthenticatedExecuteComplianceRoute
  '/execute/gantt': typeof AuthenticatedExecuteGanttRoute
  '/execute/okrs': typeof AuthenticatedExecuteOkrsRoute
  '/execute/programs': typeof AuthenticatedExecuteProgramsRoute
  '/execute/tasks': typeof AuthenticatedExecuteTasksRoute
  '/execute/touchpoints': typeof AuthenticatedExecuteTouchpointsRoute
  '/fund/asks-bank': typeof AuthenticatedFundAsksBankRoute
  '/fund/budget': typeof AuthenticatedFundBudgetRoute
  '/fund/donor-segments': typeof AuthenticatedFundDonorSegmentsRoute
  '/fund/gap': typeof AuthenticatedFundGapRoute
  '/fund/grant-bank': typeof AuthenticatedFundGrantBankRoute
  '/fund/grants': typeof AuthenticatedFundGrantsRoute
  '/fund/pipeline': typeof AuthenticatedFundPipelineRoute
  '/fund/proforma': typeof AuthenticatedFundProformaRoute
  '/fund/program-costs': typeof AuthenticatedFundProgramCostsRoute
  '/fund/reserves': typeof AuthenticatedFundReservesRoute
  '/fund/scenarios': typeof AuthenticatedFundScenariosRoute
  '/governance/board-matrix': typeof AuthenticatedGovernanceBoardMatrixRoute
  '/governance/decisions': typeof AuthenticatedGovernanceDecisionsRoute
  '/governance/meetings': typeof AuthenticatedGovernanceMeetingsRouteWithChildren
  '/governance/policies': typeof AuthenticatedGovernancePoliciesRoute
  '/governance/staff-succession': typeof AuthenticatedGovernanceStaffSuccessionRoute
  '/invite/$token': typeof AuthenticatedInviteTokenRoute
  '/plan/builder': typeof AuthenticatedPlanBuilderRoute
  '/plan/kpis': typeof AuthenticatedPlanKpisRoute
  '/plan/narrative': typeof AuthenticatedPlanNarrativeRoute
  '/plan/priorities': typeof AuthenticatedPlanPrioritiesRoute
  '/plan/risks': typeof AuthenticatedPlanRisksRoute
  '/plan/stakeholders': typeof AuthenticatedPlanStakeholdersRoute
  '/plan/swot': typeof AuthenticatedPlanSwotRoute
  '/plan/theory-of-change': typeof AuthenticatedPlanTheoryOfChangeRoute
  '/report/benchmarks': typeof AuthenticatedReportBenchmarksRoute
  '/report/exports': typeof AuthenticatedReportExportsRoute
  '/report/insights': typeof AuthenticatedReportInsightsRoute
  '/report/monthly-review': typeof AuthenticatedReportMonthlyReviewRoute
  '/report/stories': typeof AuthenticatedReportStoriesRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/orgs/$orgId': typeof AuthenticatedAdminOrgsOrgIdRoute
  '/governance/meetings/$meetingId': typeof AuthenticatedGovernanceMeetingsMeetingIdRoute
  '/report/print/action-plan-306090': typeof AuthenticatedReportPrintActionPlan306090Route
  '/report/print/annual-operating-plan': typeof AuthenticatedReportPrintAnnualOperatingPlanRoute
  '/report/print/board-packet': typeof AuthenticatedReportPrintBoardPacketRoute
  '/report/print/financial-sustainability': typeof AuthenticatedReportPrintFinancialSustainabilityRoute
  '/report/print/fourrs-report': typeof AuthenticatedReportPrintFourrsReportRoute
  '/report/print/funder-report': typeof AuthenticatedReportPrintFunderReportRoute
  '/report/print/funding-gap': typeof AuthenticatedReportPrintFundingGapRoute
  '/report/print/grant-readiness': typeof AuthenticatedReportPrintGrantReadinessRoute
  '/report/print/impact-report': typeof AuthenticatedReportPrintImpactReportRoute
  '/report/print/logic-model': typeof AuthenticatedReportPrintLogicModelRoute
  '/report/print/program-impact': typeof AuthenticatedReportPrintProgramImpactRoute
  '/report/print/revenue-diversification': typeof AuthenticatedReportPrintRevenueDiversificationRoute
  '/report/print/strategic-plan': typeof AuthenticatedReportPrintStrategicPlanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/team': typeof AuthenticatedTeamRoute
  '/values': typeof AuthenticatedValuesRoute
  '/assess/4rs': typeof AuthenticatedAssess4rsRoute
  '/assess/capacity': typeof AuthenticatedAssessCapacityRoute
  '/assess/community': typeof AuthenticatedAssessCommunityRoute
  '/assess/dei': typeof AuthenticatedAssessDeiRoute
  '/assess/digital': typeof AuthenticatedAssessDigitalRoute
  '/assess/financial': typeof AuthenticatedAssessFinancialRoute
  '/assess/fundraising': typeof AuthenticatedAssessFundraisingRoute
  '/assess/governance': typeof AuthenticatedAssessGovernanceRoute
  '/assess/health': typeof AuthenticatedAssessHealthRoute
  '/assess/impact': typeof AuthenticatedAssessImpactRoute
  '/assess/program-impact': typeof AuthenticatedAssessProgramImpactRoute
  '/assess/revenue-hhi': typeof AuthenticatedAssessRevenueHhiRoute
  '/execute/calendar': typeof AuthenticatedExecuteCalendarRoute
  '/execute/coffee-chats': typeof AuthenticatedExecuteCoffeeChatsRoute
  '/execute/compliance': typeof AuthenticatedExecuteComplianceRoute
  '/execute/gantt': typeof AuthenticatedExecuteGanttRoute
  '/execute/okrs': typeof AuthenticatedExecuteOkrsRoute
  '/execute/programs': typeof AuthenticatedExecuteProgramsRoute
  '/execute/tasks': typeof AuthenticatedExecuteTasksRoute
  '/execute/touchpoints': typeof AuthenticatedExecuteTouchpointsRoute
  '/fund/asks-bank': typeof AuthenticatedFundAsksBankRoute
  '/fund/budget': typeof AuthenticatedFundBudgetRoute
  '/fund/donor-segments': typeof AuthenticatedFundDonorSegmentsRoute
  '/fund/gap': typeof AuthenticatedFundGapRoute
  '/fund/grant-bank': typeof AuthenticatedFundGrantBankRoute
  '/fund/grants': typeof AuthenticatedFundGrantsRoute
  '/fund/pipeline': typeof AuthenticatedFundPipelineRoute
  '/fund/proforma': typeof AuthenticatedFundProformaRoute
  '/fund/program-costs': typeof AuthenticatedFundProgramCostsRoute
  '/fund/reserves': typeof AuthenticatedFundReservesRoute
  '/fund/scenarios': typeof AuthenticatedFundScenariosRoute
  '/governance/board-matrix': typeof AuthenticatedGovernanceBoardMatrixRoute
  '/governance/decisions': typeof AuthenticatedGovernanceDecisionsRoute
  '/governance/meetings': typeof AuthenticatedGovernanceMeetingsRouteWithChildren
  '/governance/policies': typeof AuthenticatedGovernancePoliciesRoute
  '/governance/staff-succession': typeof AuthenticatedGovernanceStaffSuccessionRoute
  '/invite/$token': typeof AuthenticatedInviteTokenRoute
  '/plan/builder': typeof AuthenticatedPlanBuilderRoute
  '/plan/kpis': typeof AuthenticatedPlanKpisRoute
  '/plan/narrative': typeof AuthenticatedPlanNarrativeRoute
  '/plan/priorities': typeof AuthenticatedPlanPrioritiesRoute
  '/plan/risks': typeof AuthenticatedPlanRisksRoute
  '/plan/stakeholders': typeof AuthenticatedPlanStakeholdersRoute
  '/plan/swot': typeof AuthenticatedPlanSwotRoute
  '/plan/theory-of-change': typeof AuthenticatedPlanTheoryOfChangeRoute
  '/report/benchmarks': typeof AuthenticatedReportBenchmarksRoute
  '/report/exports': typeof AuthenticatedReportExportsRoute
  '/report/insights': typeof AuthenticatedReportInsightsRoute
  '/report/monthly-review': typeof AuthenticatedReportMonthlyReviewRoute
  '/report/stories': typeof AuthenticatedReportStoriesRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/orgs/$orgId': typeof AuthenticatedAdminOrgsOrgIdRoute
  '/governance/meetings/$meetingId': typeof AuthenticatedGovernanceMeetingsMeetingIdRoute
  '/report/print/action-plan-306090': typeof AuthenticatedReportPrintActionPlan306090Route
  '/report/print/annual-operating-plan': typeof AuthenticatedReportPrintAnnualOperatingPlanRoute
  '/report/print/board-packet': typeof AuthenticatedReportPrintBoardPacketRoute
  '/report/print/financial-sustainability': typeof AuthenticatedReportPrintFinancialSustainabilityRoute
  '/report/print/fourrs-report': typeof AuthenticatedReportPrintFourrsReportRoute
  '/report/print/funder-report': typeof AuthenticatedReportPrintFunderReportRoute
  '/report/print/funding-gap': typeof AuthenticatedReportPrintFundingGapRoute
  '/report/print/grant-readiness': typeof AuthenticatedReportPrintGrantReadinessRoute
  '/report/print/impact-report': typeof AuthenticatedReportPrintImpactReportRoute
  '/report/print/logic-model': typeof AuthenticatedReportPrintLogicModelRoute
  '/report/print/program-impact': typeof AuthenticatedReportPrintProgramImpactRoute
  '/report/print/revenue-diversification': typeof AuthenticatedReportPrintRevenueDiversificationRoute
  '/report/print/strategic-plan': typeof AuthenticatedReportPrintStrategicPlanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/values': typeof AuthenticatedValuesRoute
  '/_authenticated/assess/4rs': typeof AuthenticatedAssess4rsRoute
  '/_authenticated/assess/capacity': typeof AuthenticatedAssessCapacityRoute
  '/_authenticated/assess/community': typeof AuthenticatedAssessCommunityRoute
  '/_authenticated/assess/dei': typeof AuthenticatedAssessDeiRoute
  '/_authenticated/assess/digital': typeof AuthenticatedAssessDigitalRoute
  '/_authenticated/assess/financial': typeof AuthenticatedAssessFinancialRoute
  '/_authenticated/assess/fundraising': typeof AuthenticatedAssessFundraisingRoute
  '/_authenticated/assess/governance': typeof AuthenticatedAssessGovernanceRoute
  '/_authenticated/assess/health': typeof AuthenticatedAssessHealthRoute
  '/_authenticated/assess/impact': typeof AuthenticatedAssessImpactRoute
  '/_authenticated/assess/program-impact': typeof AuthenticatedAssessProgramImpactRoute
  '/_authenticated/assess/revenue-hhi': typeof AuthenticatedAssessRevenueHhiRoute
  '/_authenticated/execute/calendar': typeof AuthenticatedExecuteCalendarRoute
  '/_authenticated/execute/coffee-chats': typeof AuthenticatedExecuteCoffeeChatsRoute
  '/_authenticated/execute/compliance': typeof AuthenticatedExecuteComplianceRoute
  '/_authenticated/execute/gantt': typeof AuthenticatedExecuteGanttRoute
  '/_authenticated/execute/okrs': typeof AuthenticatedExecuteOkrsRoute
  '/_authenticated/execute/programs': typeof AuthenticatedExecuteProgramsRoute
  '/_authenticated/execute/tasks': typeof AuthenticatedExecuteTasksRoute
  '/_authenticated/execute/touchpoints': typeof AuthenticatedExecuteTouchpointsRoute
  '/_authenticated/fund/asks-bank': typeof AuthenticatedFundAsksBankRoute
  '/_authenticated/fund/budget': typeof AuthenticatedFundBudgetRoute
  '/_authenticated/fund/donor-segments': typeof AuthenticatedFundDonorSegmentsRoute
  '/_authenticated/fund/gap': typeof AuthenticatedFundGapRoute
  '/_authenticated/fund/grant-bank': typeof AuthenticatedFundGrantBankRoute
  '/_authenticated/fund/grants': typeof AuthenticatedFundGrantsRoute
  '/_authenticated/fund/pipeline': typeof AuthenticatedFundPipelineRoute
  '/_authenticated/fund/proforma': typeof AuthenticatedFundProformaRoute
  '/_authenticated/fund/program-costs': typeof AuthenticatedFundProgramCostsRoute
  '/_authenticated/fund/reserves': typeof AuthenticatedFundReservesRoute
  '/_authenticated/fund/scenarios': typeof AuthenticatedFundScenariosRoute
  '/_authenticated/governance/board-matrix': typeof AuthenticatedGovernanceBoardMatrixRoute
  '/_authenticated/governance/decisions': typeof AuthenticatedGovernanceDecisionsRoute
  '/_authenticated/governance/meetings': typeof AuthenticatedGovernanceMeetingsRouteWithChildren
  '/_authenticated/governance/policies': typeof AuthenticatedGovernancePoliciesRoute
  '/_authenticated/governance/staff-succession': typeof AuthenticatedGovernanceStaffSuccessionRoute
  '/_authenticated/invite/$token': typeof AuthenticatedInviteTokenRoute
  '/_authenticated/plan/builder': typeof AuthenticatedPlanBuilderRoute
  '/_authenticated/plan/kpis': typeof AuthenticatedPlanKpisRoute
  '/_authenticated/plan/narrative': typeof AuthenticatedPlanNarrativeRoute
  '/_authenticated/plan/priorities': typeof AuthenticatedPlanPrioritiesRoute
  '/_authenticated/plan/risks': typeof AuthenticatedPlanRisksRoute
  '/_authenticated/plan/stakeholders': typeof AuthenticatedPlanStakeholdersRoute
  '/_authenticated/plan/swot': typeof AuthenticatedPlanSwotRoute
  '/_authenticated/plan/theory-of-change': typeof AuthenticatedPlanTheoryOfChangeRoute
  '/_authenticated/report/benchmarks': typeof AuthenticatedReportBenchmarksRoute
  '/_authenticated/report/exports': typeof AuthenticatedReportExportsRoute
  '/_authenticated/report/insights': typeof AuthenticatedReportInsightsRoute
  '/_authenticated/report/monthly-review': typeof AuthenticatedReportMonthlyReviewRoute
  '/_authenticated/report/stories': typeof AuthenticatedReportStoriesRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/orgs/$orgId': typeof AuthenticatedAdminOrgsOrgIdRoute
  '/_authenticated/governance/meetings/$meetingId': typeof AuthenticatedGovernanceMeetingsMeetingIdRoute
  '/_authenticated/report/print/action-plan-306090': typeof AuthenticatedReportPrintActionPlan306090Route
  '/_authenticated/report/print/annual-operating-plan': typeof AuthenticatedReportPrintAnnualOperatingPlanRoute
  '/_authenticated/report/print/board-packet': typeof AuthenticatedReportPrintBoardPacketRoute
  '/_authenticated/report/print/financial-sustainability': typeof AuthenticatedReportPrintFinancialSustainabilityRoute
  '/_authenticated/report/print/fourrs-report': typeof AuthenticatedReportPrintFourrsReportRoute
  '/_authenticated/report/print/funder-report': typeof AuthenticatedReportPrintFunderReportRoute
  '/_authenticated/report/print/funding-gap': typeof AuthenticatedReportPrintFundingGapRoute
  '/_authenticated/report/print/grant-readiness': typeof AuthenticatedReportPrintGrantReadinessRoute
  '/_authenticated/report/print/impact-report': typeof AuthenticatedReportPrintImpactReportRoute
  '/_authenticated/report/print/logic-model': typeof AuthenticatedReportPrintLogicModelRoute
  '/_authenticated/report/print/program-impact': typeof AuthenticatedReportPrintProgramImpactRoute
  '/_authenticated/report/print/revenue-diversification': typeof AuthenticatedReportPrintRevenueDiversificationRoute
  '/_authenticated/report/print/strategic-plan': typeof AuthenticatedReportPrintStrategicPlanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/dashboard'
    | '/onboarding'
    | '/profile'
    | '/team'
    | '/values'
    | '/assess/4rs'
    | '/assess/capacity'
    | '/assess/community'
    | '/assess/dei'
    | '/assess/digital'
    | '/assess/financial'
    | '/assess/fundraising'
    | '/assess/governance'
    | '/assess/health'
    | '/assess/impact'
    | '/assess/program-impact'
    | '/assess/revenue-hhi'
    | '/execute/calendar'
    | '/execute/coffee-chats'
    | '/execute/compliance'
    | '/execute/gantt'
    | '/execute/okrs'
    | '/execute/programs'
    | '/execute/tasks'
    | '/execute/touchpoints'
    | '/fund/asks-bank'
    | '/fund/budget'
    | '/fund/donor-segments'
    | '/fund/gap'
    | '/fund/grant-bank'
    | '/fund/grants'
    | '/fund/pipeline'
    | '/fund/proforma'
    | '/fund/program-costs'
    | '/fund/reserves'
    | '/fund/scenarios'
    | '/governance/board-matrix'
    | '/governance/decisions'
    | '/governance/meetings'
    | '/governance/policies'
    | '/governance/staff-succession'
    | '/invite/$token'
    | '/plan/builder'
    | '/plan/kpis'
    | '/plan/narrative'
    | '/plan/priorities'
    | '/plan/risks'
    | '/plan/stakeholders'
    | '/plan/swot'
    | '/plan/theory-of-change'
    | '/report/benchmarks'
    | '/report/exports'
    | '/report/insights'
    | '/report/monthly-review'
    | '/report/stories'
    | '/admin/'
    | '/admin/orgs/$orgId'
    | '/governance/meetings/$meetingId'
    | '/report/print/action-plan-306090'
    | '/report/print/annual-operating-plan'
    | '/report/print/board-packet'
    | '/report/print/financial-sustainability'
    | '/report/print/fourrs-report'
    | '/report/print/funder-report'
    | '/report/print/funding-gap'
    | '/report/print/grant-readiness'
    | '/report/print/impact-report'
    | '/report/print/logic-model'
    | '/report/print/program-impact'
    | '/report/print/revenue-diversification'
    | '/report/print/strategic-plan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/onboarding'
    | '/profile'
    | '/team'
    | '/values'
    | '/assess/4rs'
    | '/assess/capacity'
    | '/assess/community'
    | '/assess/dei'
    | '/assess/digital'
    | '/assess/financial'
    | '/assess/fundraising'
    | '/assess/governance'
    | '/assess/health'
    | '/assess/impact'
    | '/assess/program-impact'
    | '/assess/revenue-hhi'
    | '/execute/calendar'
    | '/execute/coffee-chats'
    | '/execute/compliance'
    | '/execute/gantt'
    | '/execute/okrs'
    | '/execute/programs'
    | '/execute/tasks'
    | '/execute/touchpoints'
    | '/fund/asks-bank'
    | '/fund/budget'
    | '/fund/donor-segments'
    | '/fund/gap'
    | '/fund/grant-bank'
    | '/fund/grants'
    | '/fund/pipeline'
    | '/fund/proforma'
    | '/fund/program-costs'
    | '/fund/reserves'
    | '/fund/scenarios'
    | '/governance/board-matrix'
    | '/governance/decisions'
    | '/governance/meetings'
    | '/governance/policies'
    | '/governance/staff-succession'
    | '/invite/$token'
    | '/plan/builder'
    | '/plan/kpis'
    | '/plan/narrative'
    | '/plan/priorities'
    | '/plan/risks'
    | '/plan/stakeholders'
    | '/plan/swot'
    | '/plan/theory-of-change'
    | '/report/benchmarks'
    | '/report/exports'
    | '/report/insights'
    | '/report/monthly-review'
    | '/report/stories'
    | '/admin'
    | '/admin/orgs/$orgId'
    | '/governance/meetings/$meetingId'
    | '/report/print/action-plan-306090'
    | '/report/print/annual-operating-plan'
    | '/report/print/board-packet'
    | '/report/print/financial-sustainability'
    | '/report/print/fourrs-report'
    | '/report/print/funder-report'
    | '/report/print/funding-gap'
    | '/report/print/grant-readiness'
    | '/report/print/impact-report'
    | '/report/print/logic-model'
    | '/report/print/program-impact'
    | '/report/print/revenue-diversification'
    | '/report/print/strategic-plan'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/onboarding'
    | '/_authenticated/profile'
    | '/_authenticated/team'
    | '/_authenticated/values'
    | '/_authenticated/assess/4rs'
    | '/_authenticated/assess/capacity'
    | '/_authenticated/assess/community'
    | '/_authenticated/assess/dei'
    | '/_authenticated/assess/digital'
    | '/_authenticated/assess/financial'
    | '/_authenticated/assess/fundraising'
    | '/_authenticated/assess/governance'
    | '/_authenticated/assess/health'
    | '/_authenticated/assess/impact'
    | '/_authenticated/assess/program-impact'
    | '/_authenticated/assess/revenue-hhi'
    | '/_authenticated/execute/calendar'
    | '/_authenticated/execute/coffee-chats'
    | '/_authenticated/execute/compliance'
    | '/_authenticated/execute/gantt'
    | '/_authenticated/execute/okrs'
    | '/_authenticated/execute/programs'
    | '/_authenticated/execute/tasks'
    | '/_authenticated/execute/touchpoints'
    | '/_authenticated/fund/asks-bank'
    | '/_authenticated/fund/budget'
    | '/_authenticated/fund/donor-segments'
    | '/_authenticated/fund/gap'
    | '/_authenticated/fund/grant-bank'
    | '/_authenticated/fund/grants'
    | '/_authenticated/fund/pipeline'
    | '/_authenticated/fund/proforma'
    | '/_authenticated/fund/program-costs'
    | '/_authenticated/fund/reserves'
    | '/_authenticated/fund/scenarios'
    | '/_authenticated/governance/board-matrix'
    | '/_authenticated/governance/decisions'
    | '/_authenticated/governance/meetings'
    | '/_authenticated/governance/policies'
    | '/_authenticated/governance/staff-succession'
    | '/_authenticated/invite/$token'
    | '/_authenticated/plan/builder'
    | '/_authenticated/plan/kpis'
    | '/_authenticated/plan/narrative'
    | '/_authenticated/plan/priorities'
    | '/_authenticated/plan/risks'
    | '/_authenticated/plan/stakeholders'
    | '/_authenticated/plan/swot'
    | '/_authenticated/plan/theory-of-change'
    | '/_authenticated/report/benchmarks'
    | '/_authenticated/report/exports'
    | '/_authenticated/report/insights'
    | '/_authenticated/report/monthly-review'
    | '/_authenticated/report/stories'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/orgs/$orgId'
    | '/_authenticated/governance/meetings/$meetingId'
    | '/_authenticated/report/print/action-plan-306090'
    | '/_authenticated/report/print/annual-operating-plan'
    | '/_authenticated/report/print/board-packet'
    | '/_authenticated/report/print/financial-sustainability'
    | '/_authenticated/report/print/fourrs-report'
    | '/_authenticated/report/print/funder-report'
    | '/_authenticated/report/print/funding-gap'
    | '/_authenticated/report/print/grant-readiness'
    | '/_authenticated/report/print/impact-report'
    | '/_authenticated/report/print/logic-model'
    | '/_authenticated/report/print/program-impact'
    | '/_authenticated/report/print/revenue-diversification'
    | '/_authenticated/report/print/strategic-plan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/values': {
      id: '/_authenticated/values'
      path: '/values'
      fullPath: '/values'
      preLoaderRoute: typeof AuthenticatedValuesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/report/stories': {
      id: '/_authenticated/report/stories'
      path: '/report/stories'
      fullPath: '/report/stories'
      preLoaderRoute: typeof AuthenticatedReportStoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report/monthly-review': {
      id: '/_authenticated/report/monthly-review'
      path: '/report/monthly-review'
      fullPath: '/report/monthly-review'
      preLoaderRoute: typeof AuthenticatedReportMonthlyReviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report/insights': {
      id: '/_authenticated/report/insights'
      path: '/report/insights'
      fullPath: '/report/insights'
      preLoaderRoute: typeof AuthenticatedReportInsightsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report/exports': {
      id: '/_authenticated/report/exports'
      path: '/report/exports'
      fullPath: '/report/exports'
      preLoaderRoute: typeof AuthenticatedReportExportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report/benchmarks': {
      id: '/_authenticated/report/benchmarks'
      path: '/report/benchmarks'
      fullPath: '/report/benchmarks'
      preLoaderRoute: typeof AuthenticatedReportBenchmarksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plan/theory-of-change': {
      id: '/_authenticated/plan/theory-of-change'
      path: '/plan/theory-of-change'
      fullPath: '/plan/theory-of-change'
      preLoaderRoute: typeof AuthenticatedPlanTheoryOfChangeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plan/swot': {
      id: '/_authenticated/plan/swot'
      path: '/plan/swot'
      fullPath: '/plan/swot'
      preLoaderRoute: typeof AuthenticatedPlanSwotRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plan/stakeholders': {
      id: '/_authenticated/plan/stakeholders'
      path: '/plan/stakeholders'
      fullPath: '/plan/stakeholders'
      preLoaderRoute: typeof AuthenticatedPlanStakeholdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plan/risks': {
      id: '/_authenticated/plan/risks'
      path: '/plan/risks'
      fullPath: '/plan/risks'
      preLoaderRoute: typeof AuthenticatedPlanRisksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plan/priorities': {
      id: '/_authenticated/plan/priorities'
      path: '/plan/priorities'
      fullPath: '/plan/priorities'
      preLoaderRoute: typeof AuthenticatedPlanPrioritiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plan/narrative': {
      id: '/_authenticated/plan/narrative'
      path: '/plan/narrative'
      fullPath: '/plan/narrative'
      preLoaderRoute: typeof AuthenticatedPlanNarrativeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plan/kpis': {
      id: '/_authenticated/plan/kpis'
      path: '/plan/kpis'
      fullPath: '/plan/kpis'
      preLoaderRoute: typeof AuthenticatedPlanKpisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plan/builder': {
      id: '/_authenticated/plan/builder'
      path: '/plan/builder'
      fullPath: '/plan/builder'
      preLoaderRoute: typeof AuthenticatedPlanBuilderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invite/$token': {
      id: '/_authenticated/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof AuthenticatedInviteTokenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/governance/staff-succession': {
      id: '/_authenticated/governance/staff-succession'
      path: '/governance/staff-succession'
      fullPath: '/governance/staff-succession'
      preLoaderRoute: typeof AuthenticatedGovernanceStaffSuccessionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/governance/policies': {
      id: '/_authenticated/governance/policies'
      path: '/governance/policies'
      fullPath: '/governance/policies'
      preLoaderRoute: typeof AuthenticatedGovernancePoliciesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/governance/meetings': {
      id: '/_authenticated/governance/meetings'
      path: '/governance/meetings'
      fullPath: '/governance/meetings'
      preLoaderRoute: typeof AuthenticatedGovernanceMeetingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/governance/decisions': {
      id: '/_authenticated/governance/decisions'
      path: '/governance/decisions'
      fullPath: '/governance/decisions'
      preLoaderRoute: typeof AuthenticatedGovernanceDecisionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/governance/board-matrix': {
      id: '/_authenticated/governance/board-matrix'
      path: '/governance/board-matrix'
      fullPath: '/governance/board-matrix'
      preLoaderRoute: typeof AuthenticatedGovernanceBoardMatrixRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fund/scenarios': {
      id: '/_authenticated/fund/scenarios'
      path: '/fund/scenarios'
      fullPath: '/fund/scenarios'
      preLoaderRoute: typeof AuthenticatedFundScenariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fund/reserves': {
      id: '/_authenticated/fund/reserves'
      path: '/fund/reserves'
      fullPath: '/fund/reserves'
      preLoaderRoute: typeof AuthenticatedFundReservesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fund/program-costs': {
      id: '/_authenticated/fund/program-costs'
      path: '/fund/program-costs'
      fullPath: '/fund/program-costs'
      preLoaderRoute: typeof AuthenticatedFundProgramCostsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fund/proforma': {
      id: '/_authenticated/fund/proforma'
      path: '/fund/proforma'
      fullPath: '/fund/proforma'
      preLoaderRoute: typeof AuthenticatedFundProformaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fund/pipeline': {
      id: '/_authenticated/fund/pipeline'
      path: '/fund/pipeline'
      fullPath: '/fund/pipeline'
      preLoaderRoute: typeof AuthenticatedFundPipelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fund/grants': {
      id: '/_authenticated/fund/grants'
      path: '/fund/grants'
      fullPath: '/fund/grants'
      preLoaderRoute: typeof AuthenticatedFundGrantsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fund/grant-bank': {
      id: '/_authenticated/fund/grant-bank'
      path: '/fund/grant-bank'
      fullPath: '/fund/grant-bank'
      preLoaderRoute: typeof AuthenticatedFundGrantBankRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fund/gap': {
      id: '/_authenticated/fund/gap'
      path: '/fund/gap'
      fullPath: '/fund/gap'
      preLoaderRoute: typeof AuthenticatedFundGapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fund/donor-segments': {
      id: '/_authenticated/fund/donor-segments'
      path: '/fund/donor-segments'
      fullPath: '/fund/donor-segments'
      preLoaderRoute: typeof AuthenticatedFundDonorSegmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fund/budget': {
      id: '/_authenticated/fund/budget'
      path: '/fund/budget'
      fullPath: '/fund/budget'
      preLoaderRoute: typeof AuthenticatedFundBudgetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fund/asks-bank': {
      id: '/_authenticated/fund/asks-bank'
      path: '/fund/asks-bank'
      fullPath: '/fund/asks-bank'
      preLoaderRoute: typeof AuthenticatedFundAsksBankRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/execute/touchpoints': {
      id: '/_authenticated/execute/touchpoints'
      path: '/execute/touchpoints'
      fullPath: '/execute/touchpoints'
      preLoaderRoute: typeof AuthenticatedExecuteTouchpointsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/execute/tasks': {
      id: '/_authenticated/execute/tasks'
      path: '/execute/tasks'
      fullPath: '/execute/tasks'
      preLoaderRoute: typeof AuthenticatedExecuteTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/execute/programs': {
      id: '/_authenticated/execute/programs'
      path: '/execute/programs'
      fullPath: '/execute/programs'
      preLoaderRoute: typeof AuthenticatedExecuteProgramsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/execute/okrs': {
      id: '/_authenticated/execute/okrs'
      path: '/execute/okrs'
      fullPath: '/execute/okrs'
      preLoaderRoute: typeof AuthenticatedExecuteOkrsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/execute/gantt': {
      id: '/_authenticated/execute/gantt'
      path: '/execute/gantt'
      fullPath: '/execute/gantt'
      preLoaderRoute: typeof AuthenticatedExecuteGanttRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/execute/compliance': {
      id: '/_authenticated/execute/compliance'
      path: '/execute/compliance'
      fullPath: '/execute/compliance'
      preLoaderRoute: typeof AuthenticatedExecuteComplianceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/execute/coffee-chats': {
      id: '/_authenticated/execute/coffee-chats'
      path: '/execute/coffee-chats'
      fullPath: '/execute/coffee-chats'
      preLoaderRoute: typeof AuthenticatedExecuteCoffeeChatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/execute/calendar': {
      id: '/_authenticated/execute/calendar'
      path: '/execute/calendar'
      fullPath: '/execute/calendar'
      preLoaderRoute: typeof AuthenticatedExecuteCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assess/revenue-hhi': {
      id: '/_authenticated/assess/revenue-hhi'
      path: '/assess/revenue-hhi'
      fullPath: '/assess/revenue-hhi'
      preLoaderRoute: typeof AuthenticatedAssessRevenueHhiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assess/program-impact': {
      id: '/_authenticated/assess/program-impact'
      path: '/assess/program-impact'
      fullPath: '/assess/program-impact'
      preLoaderRoute: typeof AuthenticatedAssessProgramImpactRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assess/impact': {
      id: '/_authenticated/assess/impact'
      path: '/assess/impact'
      fullPath: '/assess/impact'
      preLoaderRoute: typeof AuthenticatedAssessImpactRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assess/health': {
      id: '/_authenticated/assess/health'
      path: '/assess/health'
      fullPath: '/assess/health'
      preLoaderRoute: typeof AuthenticatedAssessHealthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assess/governance': {
      id: '/_authenticated/assess/governance'
      path: '/assess/governance'
      fullPath: '/assess/governance'
      preLoaderRoute: typeof AuthenticatedAssessGovernanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assess/fundraising': {
      id: '/_authenticated/assess/fundraising'
      path: '/assess/fundraising'
      fullPath: '/assess/fundraising'
      preLoaderRoute: typeof AuthenticatedAssessFundraisingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assess/financial': {
      id: '/_authenticated/assess/financial'
      path: '/assess/financial'
      fullPath: '/assess/financial'
      preLoaderRoute: typeof AuthenticatedAssessFinancialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assess/digital': {
      id: '/_authenticated/assess/digital'
      path: '/assess/digital'
      fullPath: '/assess/digital'
      preLoaderRoute: typeof AuthenticatedAssessDigitalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assess/dei': {
      id: '/_authenticated/assess/dei'
      path: '/assess/dei'
      fullPath: '/assess/dei'
      preLoaderRoute: typeof AuthenticatedAssessDeiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assess/community': {
      id: '/_authenticated/assess/community'
      path: '/assess/community'
      fullPath: '/assess/community'
      preLoaderRoute: typeof AuthenticatedAssessCommunityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assess/capacity': {
      id: '/_authenticated/assess/capacity'
      path: '/assess/capacity'
      fullPath: '/assess/capacity'
      preLoaderRoute: typeof AuthenticatedAssessCapacityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assess/4rs': {
      id: '/_authenticated/assess/4rs'
      path: '/assess/4rs'
      fullPath: '/assess/4rs'
      preLoaderRoute: typeof AuthenticatedAssess4rsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report/print/strategic-plan': {
      id: '/_authenticated/report/print/strategic-plan'
      path: '/report/print/strategic-plan'
      fullPath: '/report/print/strategic-plan'
      preLoaderRoute: typeof AuthenticatedReportPrintStrategicPlanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report/print/revenue-diversification': {
      id: '/_authenticated/report/print/revenue-diversification'
      path: '/report/print/revenue-diversification'
      fullPath: '/report/print/revenue-diversification'
      preLoaderRoute: typeof AuthenticatedReportPrintRevenueDiversificationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report/print/program-impact': {
      id: '/_authenticated/report/print/program-impact'
      path: '/report/print/program-impact'
      fullPath: '/report/print/program-impact'
      preLoaderRoute: typeof AuthenticatedReportPrintProgramImpactRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report/print/logic-model': {
      id: '/_authenticated/report/print/logic-model'
      path: '/report/print/logic-model'
      fullPath: '/report/print/logic-model'
      preLoaderRoute: typeof AuthenticatedReportPrintLogicModelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report/print/impact-report': {
      id: '/_authenticated/report/print/impact-report'
      path: '/report/print/impact-report'
      fullPath: '/report/print/impact-report'
      preLoaderRoute: typeof AuthenticatedReportPrintImpactReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report/print/grant-readiness': {
      id: '/_authenticated/report/print/grant-readiness'
      path: '/report/print/grant-readiness'
      fullPath: '/report/print/grant-readiness'
      preLoaderRoute: typeof AuthenticatedReportPrintGrantReadinessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report/print/funding-gap': {
      id: '/_authenticated/report/print/funding-gap'
      path: '/report/print/funding-gap'
      fullPath: '/report/print/funding-gap'
      preLoaderRoute: typeof AuthenticatedReportPrintFundingGapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report/print/funder-report': {
      id: '/_authenticated/report/print/funder-report'
      path: '/report/print/funder-report'
      fullPath: '/report/print/funder-report'
      preLoaderRoute: typeof AuthenticatedReportPrintFunderReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report/print/fourrs-report': {
      id: '/_authenticated/report/print/fourrs-report'
      path: '/report/print/fourrs-report'
      fullPath: '/report/print/fourrs-report'
      preLoaderRoute: typeof AuthenticatedReportPrintFourrsReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report/print/financial-sustainability': {
      id: '/_authenticated/report/print/financial-sustainability'
      path: '/report/print/financial-sustainability'
      fullPath: '/report/print/financial-sustainability'
      preLoaderRoute: typeof AuthenticatedReportPrintFinancialSustainabilityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report/print/board-packet': {
      id: '/_authenticated/report/print/board-packet'
      path: '/report/print/board-packet'
      fullPath: '/report/print/board-packet'
      preLoaderRoute: typeof AuthenticatedReportPrintBoardPacketRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report/print/annual-operating-plan': {
      id: '/_authenticated/report/print/annual-operating-plan'
      path: '/report/print/annual-operating-plan'
      fullPath: '/report/print/annual-operating-plan'
      preLoaderRoute: typeof AuthenticatedReportPrintAnnualOperatingPlanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report/print/action-plan-306090': {
      id: '/_authenticated/report/print/action-plan-306090'
      path: '/report/print/action-plan-306090'
      fullPath: '/report/print/action-plan-306090'
      preLoaderRoute: typeof AuthenticatedReportPrintActionPlan306090RouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/governance/meetings/$meetingId': {
      id: '/_authenticated/governance/meetings/$meetingId'
      path: '/$meetingId'
      fullPath: '/governance/meetings/$meetingId'
      preLoaderRoute: typeof AuthenticatedGovernanceMeetingsMeetingIdRouteImport
      parentRoute: typeof AuthenticatedGovernanceMeetingsRoute
    }
    '/_authenticated/admin/orgs/$orgId': {
      id: '/_authenticated/admin/orgs/$orgId'
      path: '/orgs/$orgId'
      fullPath: '/admin/orgs/$orgId'
      preLoaderRoute: typeof AuthenticatedAdminOrgsOrgIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminOrgsOrgIdRoute: typeof AuthenticatedAdminOrgsOrgIdRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminOrgsOrgIdRoute: AuthenticatedAdminOrgsOrgIdRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedGovernanceMeetingsRouteChildren {
  AuthenticatedGovernanceMeetingsMeetingIdRoute: typeof AuthenticatedGovernanceMeetingsMeetingIdRoute
}

const AuthenticatedGovernanceMeetingsRouteChildren: AuthenticatedGovernanceMeetingsRouteChildren =
  {
    AuthenticatedGovernanceMeetingsMeetingIdRoute:
      AuthenticatedGovernanceMeetingsMeetingIdRoute,
  }

const AuthenticatedGovernanceMeetingsRouteWithChildren =
  AuthenticatedGovernanceMeetingsRoute._addFileChildren(
    AuthenticatedGovernanceMeetingsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedValuesRoute: typeof AuthenticatedValuesRoute
  AuthenticatedAssess4rsRoute: typeof AuthenticatedAssess4rsRoute
  AuthenticatedAssessCapacityRoute: typeof AuthenticatedAssessCapacityRoute
  AuthenticatedAssessCommunityRoute: typeof AuthenticatedAssessCommunityRoute
  AuthenticatedAssessDeiRoute: typeof AuthenticatedAssessDeiRoute
  AuthenticatedAssessDigitalRoute: typeof AuthenticatedAssessDigitalRoute
  AuthenticatedAssessFinancialRoute: typeof AuthenticatedAssessFinancialRoute
  AuthenticatedAssessFundraisingRoute: typeof AuthenticatedAssessFundraisingRoute
  AuthenticatedAssessGovernanceRoute: typeof AuthenticatedAssessGovernanceRoute
  AuthenticatedAssessHealthRoute: typeof AuthenticatedAssessHealthRoute
  AuthenticatedAssessImpactRoute: typeof AuthenticatedAssessImpactRoute
  AuthenticatedAssessProgramImpactRoute: typeof AuthenticatedAssessProgramImpactRoute
  AuthenticatedAssessRevenueHhiRoute: typeof AuthenticatedAssessRevenueHhiRoute
  AuthenticatedExecuteCalendarRoute: typeof AuthenticatedExecuteCalendarRoute
  AuthenticatedExecuteCoffeeChatsRoute: typeof AuthenticatedExecuteCoffeeChatsRoute
  AuthenticatedExecuteComplianceRoute: typeof AuthenticatedExecuteComplianceRoute
  AuthenticatedExecuteGanttRoute: typeof AuthenticatedExecuteGanttRoute
  AuthenticatedExecuteOkrsRoute: typeof AuthenticatedExecuteOkrsRoute
  AuthenticatedExecuteProgramsRoute: typeof AuthenticatedExecuteProgramsRoute
  AuthenticatedExecuteTasksRoute: typeof AuthenticatedExecuteTasksRoute
  AuthenticatedExecuteTouchpointsRoute: typeof AuthenticatedExecuteTouchpointsRoute
  AuthenticatedFundAsksBankRoute: typeof AuthenticatedFundAsksBankRoute
  AuthenticatedFundBudgetRoute: typeof AuthenticatedFundBudgetRoute
  AuthenticatedFundDonorSegmentsRoute: typeof AuthenticatedFundDonorSegmentsRoute
  AuthenticatedFundGapRoute: typeof AuthenticatedFundGapRoute
  AuthenticatedFundGrantBankRoute: typeof AuthenticatedFundGrantBankRoute
  AuthenticatedFundGrantsRoute: typeof AuthenticatedFundGrantsRoute
  AuthenticatedFundPipelineRoute: typeof AuthenticatedFundPipelineRoute
  AuthenticatedFundProformaRoute: typeof AuthenticatedFundProformaRoute
  AuthenticatedFundProgramCostsRoute: typeof AuthenticatedFundProgramCostsRoute
  AuthenticatedFundReservesRoute: typeof AuthenticatedFundReservesRoute
  AuthenticatedFundScenariosRoute: typeof AuthenticatedFundScenariosRoute
  AuthenticatedGovernanceBoardMatrixRoute: typeof AuthenticatedGovernanceBoardMatrixRoute
  AuthenticatedGovernanceDecisionsRoute: typeof AuthenticatedGovernanceDecisionsRoute
  AuthenticatedGovernanceMeetingsRoute: typeof AuthenticatedGovernanceMeetingsRouteWithChildren
  AuthenticatedGovernancePoliciesRoute: typeof AuthenticatedGovernancePoliciesRoute
  AuthenticatedGovernanceStaffSuccessionRoute: typeof AuthenticatedGovernanceStaffSuccessionRoute
  AuthenticatedInviteTokenRoute: typeof AuthenticatedInviteTokenRoute
  AuthenticatedPlanBuilderRoute: typeof AuthenticatedPlanBuilderRoute
  AuthenticatedPlanKpisRoute: typeof AuthenticatedPlanKpisRoute
  AuthenticatedPlanNarrativeRoute: typeof AuthenticatedPlanNarrativeRoute
  AuthenticatedPlanPrioritiesRoute: typeof AuthenticatedPlanPrioritiesRoute
  AuthenticatedPlanRisksRoute: typeof AuthenticatedPlanRisksRoute
  AuthenticatedPlanStakeholdersRoute: typeof AuthenticatedPlanStakeholdersRoute
  AuthenticatedPlanSwotRoute: typeof AuthenticatedPlanSwotRoute
  AuthenticatedPlanTheoryOfChangeRoute: typeof AuthenticatedPlanTheoryOfChangeRoute
  AuthenticatedReportBenchmarksRoute: typeof AuthenticatedReportBenchmarksRoute
  AuthenticatedReportExportsRoute: typeof AuthenticatedReportExportsRoute
  AuthenticatedReportInsightsRoute: typeof AuthenticatedReportInsightsRoute
  AuthenticatedReportMonthlyReviewRoute: typeof AuthenticatedReportMonthlyReviewRoute
  AuthenticatedReportStoriesRoute: typeof AuthenticatedReportStoriesRoute
  AuthenticatedReportPrintActionPlan306090Route: typeof AuthenticatedReportPrintActionPlan306090Route
  AuthenticatedReportPrintAnnualOperatingPlanRoute: typeof AuthenticatedReportPrintAnnualOperatingPlanRoute
  AuthenticatedReportPrintBoardPacketRoute: typeof AuthenticatedReportPrintBoardPacketRoute
  AuthenticatedReportPrintFinancialSustainabilityRoute: typeof AuthenticatedReportPrintFinancialSustainabilityRoute
  AuthenticatedReportPrintFourrsReportRoute: typeof AuthenticatedReportPrintFourrsReportRoute
  AuthenticatedReportPrintFunderReportRoute: typeof AuthenticatedReportPrintFunderReportRoute
  AuthenticatedReportPrintFundingGapRoute: typeof AuthenticatedReportPrintFundingGapRoute
  AuthenticatedReportPrintGrantReadinessRoute: typeof AuthenticatedReportPrintGrantReadinessRoute
  AuthenticatedReportPrintImpactReportRoute: typeof AuthenticatedReportPrintImpactReportRoute
  AuthenticatedReportPrintLogicModelRoute: typeof AuthenticatedReportPrintLogicModelRoute
  AuthenticatedReportPrintProgramImpactRoute: typeof AuthenticatedReportPrintProgramImpactRoute
  AuthenticatedReportPrintRevenueDiversificationRoute: typeof AuthenticatedReportPrintRevenueDiversificationRoute
  AuthenticatedReportPrintStrategicPlanRoute: typeof AuthenticatedReportPrintStrategicPlanRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedValuesRoute: AuthenticatedValuesRoute,
  AuthenticatedAssess4rsRoute: AuthenticatedAssess4rsRoute,
  AuthenticatedAssessCapacityRoute: AuthenticatedAssessCapacityRoute,
  AuthenticatedAssessCommunityRoute: AuthenticatedAssessCommunityRoute,
  AuthenticatedAssessDeiRoute: AuthenticatedAssessDeiRoute,
  AuthenticatedAssessDigitalRoute: AuthenticatedAssessDigitalRoute,
  AuthenticatedAssessFinancialRoute: AuthenticatedAssessFinancialRoute,
  AuthenticatedAssessFundraisingRoute: AuthenticatedAssessFundraisingRoute,
  AuthenticatedAssessGovernanceRoute: AuthenticatedAssessGovernanceRoute,
  AuthenticatedAssessHealthRoute: AuthenticatedAssessHealthRoute,
  AuthenticatedAssessImpactRoute: AuthenticatedAssessImpactRoute,
  AuthenticatedAssessProgramImpactRoute: AuthenticatedAssessProgramImpactRoute,
  AuthenticatedAssessRevenueHhiRoute: AuthenticatedAssessRevenueHhiRoute,
  AuthenticatedExecuteCalendarRoute: AuthenticatedExecuteCalendarRoute,
  AuthenticatedExecuteCoffeeChatsRoute: AuthenticatedExecuteCoffeeChatsRoute,
  AuthenticatedExecuteComplianceRoute: AuthenticatedExecuteComplianceRoute,
  AuthenticatedExecuteGanttRoute: AuthenticatedExecuteGanttRoute,
  AuthenticatedExecuteOkrsRoute: AuthenticatedExecuteOkrsRoute,
  AuthenticatedExecuteProgramsRoute: AuthenticatedExecuteProgramsRoute,
  AuthenticatedExecuteTasksRoute: AuthenticatedExecuteTasksRoute,
  AuthenticatedExecuteTouchpointsRoute: AuthenticatedExecuteTouchpointsRoute,
  AuthenticatedFundAsksBankRoute: AuthenticatedFundAsksBankRoute,
  AuthenticatedFundBudgetRoute: AuthenticatedFundBudgetRoute,
  AuthenticatedFundDonorSegmentsRoute: AuthenticatedFundDonorSegmentsRoute,
  AuthenticatedFundGapRoute: AuthenticatedFundGapRoute,
  AuthenticatedFundGrantBankRoute: AuthenticatedFundGrantBankRoute,
  AuthenticatedFundGrantsRoute: AuthenticatedFundGrantsRoute,
  AuthenticatedFundPipelineRoute: AuthenticatedFundPipelineRoute,
  AuthenticatedFundProformaRoute: AuthenticatedFundProformaRoute,
  AuthenticatedFundProgramCostsRoute: AuthenticatedFundProgramCostsRoute,
  AuthenticatedFundReservesRoute: AuthenticatedFundReservesRoute,
  AuthenticatedFundScenariosRoute: AuthenticatedFundScenariosRoute,
  AuthenticatedGovernanceBoardMatrixRoute:
    AuthenticatedGovernanceBoardMatrixRoute,
  AuthenticatedGovernanceDecisionsRoute: AuthenticatedGovernanceDecisionsRoute,
  AuthenticatedGovernanceMeetingsRoute:
    AuthenticatedGovernanceMeetingsRouteWithChildren,
  AuthenticatedGovernancePoliciesRoute: AuthenticatedGovernancePoliciesRoute,
  AuthenticatedGovernanceStaffSuccessionRoute:
    AuthenticatedGovernanceStaffSuccessionRoute,
  AuthenticatedInviteTokenRoute: AuthenticatedInviteTokenRoute,
  AuthenticatedPlanBuilderRoute: AuthenticatedPlanBuilderRoute,
  AuthenticatedPlanKpisRoute: AuthenticatedPlanKpisRoute,
  AuthenticatedPlanNarrativeRoute: AuthenticatedPlanNarrativeRoute,
  AuthenticatedPlanPrioritiesRoute: AuthenticatedPlanPrioritiesRoute,
  AuthenticatedPlanRisksRoute: AuthenticatedPlanRisksRoute,
  AuthenticatedPlanStakeholdersRoute: AuthenticatedPlanStakeholdersRoute,
  AuthenticatedPlanSwotRoute: AuthenticatedPlanSwotRoute,
  AuthenticatedPlanTheoryOfChangeRoute: AuthenticatedPlanTheoryOfChangeRoute,
  AuthenticatedReportBenchmarksRoute: AuthenticatedReportBenchmarksRoute,
  AuthenticatedReportExportsRoute: AuthenticatedReportExportsRoute,
  AuthenticatedReportInsightsRoute: AuthenticatedReportInsightsRoute,
  AuthenticatedReportMonthlyReviewRoute: AuthenticatedReportMonthlyReviewRoute,
  AuthenticatedReportStoriesRoute: AuthenticatedReportStoriesRoute,
  AuthenticatedReportPrintActionPlan306090Route:
    AuthenticatedReportPrintActionPlan306090Route,
  AuthenticatedReportPrintAnnualOperatingPlanRoute:
    AuthenticatedReportPrintAnnualOperatingPlanRoute,
  AuthenticatedReportPrintBoardPacketRoute:
    AuthenticatedReportPrintBoardPacketRoute,
  AuthenticatedReportPrintFinancialSustainabilityRoute:
    AuthenticatedReportPrintFinancialSustainabilityRoute,
  AuthenticatedReportPrintFourrsReportRoute:
    AuthenticatedReportPrintFourrsReportRoute,
  AuthenticatedReportPrintFunderReportRoute:
    AuthenticatedReportPrintFunderReportRoute,
  AuthenticatedReportPrintFundingGapRoute:
    AuthenticatedReportPrintFundingGapRoute,
  AuthenticatedReportPrintGrantReadinessRoute:
    AuthenticatedReportPrintGrantReadinessRoute,
  AuthenticatedReportPrintImpactReportRoute:
    AuthenticatedReportPrintImpactReportRoute,
  AuthenticatedReportPrintLogicModelRoute:
    AuthenticatedReportPrintLogicModelRoute,
  AuthenticatedReportPrintProgramImpactRoute:
    AuthenticatedReportPrintProgramImpactRoute,
  AuthenticatedReportPrintRevenueDiversificationRoute:
    AuthenticatedReportPrintRevenueDiversificationRoute,
  AuthenticatedReportPrintStrategicPlanRoute:
    AuthenticatedReportPrintStrategicPlanRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
